In [ ]:
import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")
print("This exercise covers Python fundamentals, data structures, functions,")
print("core libraries (os, datetime, random), file handling, and exception handling.")
print("Estimated completion time: 3-4 hours.")
print("------------------------------------------")

# --- Global Data for the Exercise (Simulated Data) ---
# We'll imagine this is sensor data from various devices.
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']
READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0), # Celsius
    'Humidity_Sensor': (30.0, 80.0),   # Percentage
    'Pressure_Sensor': (980.0, 1030.0),# hPa
    'Light_Sensor': (100, 1000)        # Lux
}

# --- Task 1: Python Fundamentals, Lists, Tuples, Sets, Dictionaries, Indexing & Slicing ---
print("\n--- Task 1: Data Generation and Basic Structures ---")


# 1.1 Generate a list of 100 simulated sensor readings.
#    Each reading should be a tuple: (timestamp_str, device_id, device_type, location, value).
#    - timestamp_str: Format as 'YYYY-MM-DD HH:MM:SS'
#    - device_id: A unique ID for each reading (e.g., 'DEV001', 'DEV002', etc., up to 100 unique IDs).
#    - device_type: Randomly chosen from DEVICE_TYPES.
#    - location: Randomly chosen from LOCATIONS.
#    - value: Random float within READING_RANGES for its device_type (round to 2 decimal places).
# Store these in a list called 'raw_sensor_data'.

# Your code for Task 1.1 here:





# 1.2 From 'raw_sensor_data', create a list named 'temperature_readings' containing only the readings
#     where 'device_type' is 'Temperature_Sensor'.
#     Each item in 'temperature_readings' should be a dictionary with keys:
#     'timestamp', 'device_id', 'location', 'temperature_celsius'.

# Your code for Task 1.2 here:




# 1.3 Create a set named 'unique_locations' containing all unique locations from 'raw_sensor_data'.

# Your code for Task 1.3 here:



# 1.4 Create a dictionary named 'device_stats' where keys are 'device_type' and values are
#     a tuple: (min_value, max_value) observed for that device type across all readings.
#     Initialize with sensible large/small values.

# Your code for Task 1.4 here:




# 1.5: Advanced Indexing and Slicing (Lists and Strings)
print("\n--- Task 1.5: Advanced Indexing and Slicing (Lists and Strings) ---")

# Let's use 'raw_sensor_data' and create a sample string for these tasks.
sample_string = "PythonProgrammingIsFun"

# 1.5.1 List Slicing: Extract elements from the 10th to the 20th (inclusive) from 'raw_sensor_data'.
#       Store the result in 'sliced_readings_1'.
#       Then, extract every 5th reading from 'raw_sensor_data' starting from the beginning.
#       Store the result in 'sliced_readings_2'.

# Your code for Task 1.5.1 here:



# 1.5.2 String Slicing: Extract the substring "Programming" from 'sample_string'.
#       Store the result in 'substring_1'.
#       Then, extract the substring "nohtyP" (the reverse of "Python") from 'sample_string' using slicing.
#       Store the result in 'substring_2'.

# Your code for Task 1.5.2 here:



# 1.5.3 Mixed Slicing: Access the 'device_type' of the 5th reading in 'raw_sensor_data' using indexing.
#       Store it in 'fifth_reading_device_type'.
#       Then, from 'fifth_reading_device_type', extract the last 6 characters (e.g., 'Sensor' from 'Temperature_Sensor').
#       Store it in 'device_type_suffix'.

# Your code for Task 1.5.3 here:




# --- Task 2: Writing and Using Functions in Python ---
print("\n--- Task 2: Function Definitions and Usage ---")

# 2.1 Write a function `get_readings_by_location(readings_list, target_location)`
#     that takes the 'raw_sensor_data' list and a 'target_location' string.
#     It should return a list of all readings (as tuples) for that specific location.

# Your code for Task 2.1 here:


# 2.2 Write a function `calculate_average_temperature(temp_data_list)`
#     that takes the 'temperature_readings' list (list of dictionaries).
#     It should calculate and return the average temperature. Return 0.0 if the list is empty.

# Your code for Task 2.2 here:



# 2.3 Write a function `generate_report_line(reading_dict)`
#     that takes a single temperature reading dictionary.
#     It should return a formatted string like:
#     "[{timestamp}] Device {device_id} at {location}: {temperature_celsius}°C"

# Your code for Task 2.3 here:



# --- Task 3: Working with Core Python Libraries (os, datetime, random) ---
print("\n--- Task 3: Core Library Usage ---")

# 3.1 Use the `os` module to create a new directory named 'sensor_reports'
#     in the current working directory, if it doesn't already exist.

# Your code for Task 3.1 here:
reports_dir = 'sensor_reports'
if not os.path.exists(reports_dir):
    os.makedirs(reports_dir)
    print(f"\nDirectory '{reports_dir}' created.")
else:
    print(f"\nDirectory '{reports_dir}' already exists.")


# 3.2 Calculate the duration between the first and last timestamp in 'raw_sensor_data'.
#     Convert string timestamps to datetime objects first.
#     Print the duration in days, hours, and minutes.

# Your code for Task 3.2 here:
if len(raw_sensor_data) > 1:
    first_timestamp_str = raw_sensor_data[0][0]
    last_timestamp_str = raw_sensor_data[-1][0]

    # Convert string to datetime object
    # The format string must exactly match the timestamp string
    date_format = '%Y-%m-%d %H:%M:%S'
    first_dt = datetime.datetime.strptime(first_timestamp_str, date_format)
    last_dt = datetime.datetime.strptime(last_timestamp_str, date_format)

    duration = last_dt - first_dt

    days = duration.days
    seconds = duration.total_seconds()
    hours = int(seconds // 3600) % 24 # Calculate remaining hours after full days
    minutes = int((seconds % 3600) // 60) # Calculate remaining minutes after full hours

    print(f"\nDuration of data collection: {days} days, {hours} hours, {minutes} minutes.")
else:
    print("\nNot enough data to calculate duration.")


# 3.3 Generate a list of 5 random integer values between 100 and 200 (inclusive)
#     using the `random` module. Store it in 'random_values'.

# Your code for Task 3.3 here:



# --- Task 4: File Handling in Python ---
print("\n--- Task 4: File I/O ---")

# 4.1 Write all 'temperature_readings' to a file named 'sensor_reports/temperature_report.txt'.
#     Each line in the file should be generated using the `generate_report_line` function.

# Your code for Task 4.1 here:
report_filename = os.path.join(reports_dir, 'temperature_report.txt')
try:
    with open(report_filename, 'w') as f:
        for reading_dict in temperature_readings:
            line = generate_report_line(reading_dict)
            f.write(line + '\n')
    print(f"\nTemperature report written to '{report_filename}'.")
except IOError as e:
    print(f"\nError writing file '{report_filename}': {e}")


# 4.2 Read the content of 'sensor_reports/temperature_report.txt' back into a list of strings
#     named 'read_report_lines'. Print the first 3 lines.

# Your code for Task 4.2 here:





print("\n--- Exercise Complete! ---")
print("Great job completing the intermediate Python exercise.")
print("Review your code and outputs to ensure correctness and understanding of all concepts.")
print("Consider adding more complex scenarios or user inputs for further practice.")

In [21]:
import os
import datetime
import random

print("--- Intermediate Python Core Exercise ---")

# Global Data
DEVICE_TYPES = ['Temperature_Sensor', 'Humidity_Sensor', 'Pressure_Sensor', 'Light_Sensor']
LOCATIONS = ['Lab1', 'Lab2', 'OfficeA', 'OfficeB', 'Warehouse']

READING_RANGES = {
    'Temperature_Sensor': (18.0, 30.0),
    'Humidity_Sensor': (30.0, 80.0),
    'Pressure_Sensor': (980.0, 1030.0),
    'Light_Sensor': (100, 1000)
}

# --------------------------------------------------
# Task 1.1 Generate Sensor Data
# --------------------------------------------------

raw_sensor_data = []

for i in range(100):
    device_type = random.choice(DEVICE_TYPES)
    location = random.choice(LOCATIONS)

    min_val, max_val = READING_RANGES[device_type]
    value = round(random.uniform(min_val, max_val), 2)

    timestamp = (
        datetime.datetime.now() +
        datetime.timedelta(minutes=i)
    ).strftime('%Y-%m-%d %H:%M:%S')

    device_id = f"DEV{i+1:03d}"

    raw_sensor_data.append(
        (timestamp, device_id, device_type, location, value)
    )

# --------------------------------------------------
# Task 1.2 Temperature Readings
# --------------------------------------------------

temperature_readings = []

for reading in raw_sensor_data:
    if reading[2] == "Temperature_Sensor":
        temp_dict = {
            "timestamp": reading[0],
            "device_id": reading[1],
            "location": reading[3],
            "temperature_celsius": reading[4]
        }
        temperature_readings.append(temp_dict)

# --------------------------------------------------
# Task 1.3 Unique Locations
# --------------------------------------------------

unique_locations = set()

for reading in raw_sensor_data:
    unique_locations.add(reading[3])

print("\nUnique Locations:")
print(unique_locations)

# --------------------------------------------------
# Task 1.4 Device Stats
# --------------------------------------------------

device_stats = {}

for device in DEVICE_TYPES:
    values = []

    for reading in raw_sensor_data:
        if reading[2] == device:
            values.append(reading[4])

    if values:
        device_stats[device] = (min(values), max(values))

print("\nDevice Stats:")
print(device_stats)

# --------------------------------------------------
# Task 1.5 Advanced Indexing and Slicing
# --------------------------------------------------

sample_string = "PythonProgrammingIsFun"

sliced_readings_1 = raw_sensor_data[9:20]
sliced_readings_2 = raw_sensor_data[::5]

substring_1 = sample_string[6:17]
substring_2 = sample_string[0:6][::-1]

fifth_reading_device_type = raw_sensor_data[4][2]
device_type_suffix = fifth_reading_device_type[-6:]

print("\nSubstring 1:", substring_1)
print("Substring 2:", substring_2)
print("5th Device Type:", fifth_reading_device_type)
print("Suffix:", device_type_suffix)

# --------------------------------------------------
# Task 2.1 Function
# --------------------------------------------------

def get_readings_by_location(readings_list, target_location):
    result = []

    for reading in readings_list:
        if reading[3] == target_location:
            result.append(reading)

    return result

# --------------------------------------------------
# Task 2.2 Function
# --------------------------------------------------

def calculate_average_temperature(temp_data_list):

    if len(temp_data_list) == 0:
        return 0.0

    total = 0

    for item in temp_data_list:
        total += item["temperature_celsius"]

    return total / len(temp_data_list)

# --------------------------------------------------
# Task 2.3 Function
# --------------------------------------------------

def generate_report_line(reading_dict):
    return (
        f"[{reading_dict['timestamp']}] "
        f"Device {reading_dict['device_id']} "
        f"at {reading_dict['location']}: "
        f"{reading_dict['temperature_celsius']}°C"
    )

avg_temp = calculate_average_temperature(temperature_readings)

print("\nAverage Temperature:", round(avg_temp, 2))

# --------------------------------------------------
# Task 3.1 Create Directory
# --------------------------------------------------

reports_dir = "sensor_reports"

if not os.path.exists(reports_dir):
    os.makedirs(reports_dir)
    print("\nDirectory created.")
else:
    print("\nDirectory already exists.")

# --------------------------------------------------
# Task 3.2 Duration Calculation
# --------------------------------------------------

if len(raw_sensor_data) > 1:

    first_timestamp = raw_sensor_data[0][0]
    last_timestamp = raw_sensor_data[-1][0]

    format_str = "%Y-%m-%d %H:%M:%S"

    first_dt = datetime.datetime.strptime(
        first_timestamp,
        format_str
    )

    last_dt = datetime.datetime.strptime(
        last_timestamp,
        format_str
    )

    duration = last_dt - first_dt

    days = duration.days
    hours = duration.seconds // 3600
    minutes = (duration.seconds % 3600) // 60

    print(
        f"\nDuration: {days} days, "
        f"{hours} hours, {minutes} minutes"
    )

# --------------------------------------------------
# Task 3.3 Random Values
# --------------------------------------------------

random_values = []

for i in range(5):
    random_values.append(random.randint(100, 200))

print("\nRandom Values:")
print(random_values)

# --------------------------------------------------
# Task 4.1 Write Report File
# --------------------------------------------------

report_filename = os.path.join(
    reports_dir,
    "temperature_report.txt"
)

try:
    with open(report_filename, "w") as file:

        for reading in temperature_readings:
            line = generate_report_line(reading)
            file.write(line + "\n")

    print("\nTemperature report written successfully.")

except IOError as e:
    print("Error:", e)

# --------------------------------------------------
# Task 4.2 Read Report File
# --------------------------------------------------

read_report_lines = []

try:
    with open(report_filename, "r") as file:
        read_report_lines = file.readlines()

    print("\nFirst 3 Lines of Report:")

    for line in read_report_lines[:3]:
        print(line.strip())

except IOError as e:
    print("Error:", e)

print("\n--- Exercise Complete! ---")

--- Intermediate Python Core Exercise ---

Unique Locations:
{'Lab1', 'OfficeB', 'Warehouse', 'OfficeA', 'Lab2'}

Device Stats:
{'Temperature_Sensor': (18.3, 29.55), 'Humidity_Sensor': (33.16, 79.71), 'Pressure_Sensor': (984.14, 1023.95), 'Light_Sensor': (167.75, 964.19)}

Substring 1: Programming
Substring 2: nohtyP
5th Device Type: Light_Sensor
Suffix: Sensor

Average Temperature: 24.6

Directory already exists.

Duration: 0 days, 1 hours, 39 minutes

Random Values:
[169, 114, 186, 127, 147]

Temperature report written successfully.

First 3 Lines of Report:
[2026-06-10 11:37:06] Device DEV004 at Lab1: 25.07°C
[2026-06-10 11:41:06] Device DEV008 at OfficeA: 20.69°C
[2026-06-10 11:44:06] Device DEV011 at Warehouse: 29.54°C

--- Exercise Complete! ---


In [2]:
import numpy as np

u = np.array([2, 3])
v = np.array([4, 1])

print("u + v =", u + v)      # [6, 4]
print("3 * u =", 3 * u)      # [6, 9]

u + v = [6 4]
3 * u = [6 9]


In [3]:
#dot product
dot1 = np.dot(u, v)          # 2*4 + 3*1 = 11
dot2 = u @ v                 # Same result

cos_theta = np.dot(u, v) / (
    np.linalg.norm(u) * np.linalg.norm(v)
)

theta = np.arccos(cos_theta)

print(f"Angle: {np.degrees(theta):.1f}°")

Angle: 42.3°


In [4]:
#Norms
w = np.array([3, -4])

print("L1:", np.linalg.norm(w, 1))       # 7.0
print("L2:", np.linalg.norm(w, 2))       # 5.0
print("Linf:", np.linalg.norm(w, np.inf))# 4.0

from sklearn.metrics.pairwise import cosine_similarity

a = np.array([[1, 2, 3]])
b = np.array([[2, 4, 6]])

print(cosine_similarity(a, b))           # [[1.0]]

L1: 7.0
L2: 5.0
Linf: 4.0
[[1.]]


**Linear Algebra**

 Exercise

* Create three vectors representing student exam scores in *[Math, Science, English]*.
* Compute *L2 norms* (overall performance).
* Compute *cosine similarity* between pairs (similar performance patterns?).
* Interpret the results.

In [8]:
import numpy as np

u = np.array([67,78,89])
v = np.array([78, 87,99])
z = np.array([50,60,90])

print("A =", u )
print("B =", v )
print("C =", z )


A = [67 78 89]
B = [78 87 99]
C = [50 60 90]


In [10]:
print("A:", np.linalg.norm(u))
print("B:", np.linalg.norm(v))
print("C:", np.linalg.norm(z))

A: 135.99264686004167
B: 153.14698821720262
C: 119.16375287812986


In [11]:
print("\nA vs B:")
print(cosine_similarity([u], [v]))


A vs B:
[[0.99981446]]


In [9]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

student1 = np.array([85, 90, 80])
student2 = np.array([88, 92, 84])
student3 = np.array([60, 95, 70])

# L2 Norms
print("Student 1:", np.linalg.norm(student1))
print("Student 2:", np.linalg.norm(student2))
print("Student 3:", np.linalg.norm(student3))

# Cosine Similarity
print("\nS1 vs S2:")
print(cosine_similarity([student1], [student2]))

print("\nS1 vs S3:")
print(cosine_similarity([student1], [student3]))

print("\nS2 vs S3:")
print(cosine_similarity([student2], [student3]))

Student 1: 147.39402972983675
Student 2: 152.52540771950095
Student 3: 132.38202294873727

S1 vs S2:
[[0.99994064]]

S1 vs S3:
[[0.98655619]]

S2 vs S3:
[[0.98555728]]


**Matrix Operations on NumPy**

In [12]:
# 🛠 Hands-On #2: Matrix Operations in NumPy

## Matrix Creation & Basic Ops

import numpy as np

A = np.array([[2, 1], [0, 3]])
B = np.array([[1, 4], [2, 5]])

print("A + B =\n", A + B)
print("A transpose =\n", A.T)
print("A @ B =\n", A @ B)    # Matrix multiplication

## Identity & Inverse


I = np.eye(3)                # 3x3 identity matrix
print("Identity:\n", I)

A = np.array([[2, 1], [1, 3]])
A_inv = np.linalg.inv(A)

print("A inverse:\n", A_inv)
print("A @ A_inv =\n", A @ A_inv)   # Should be identity


## Solving Ax = b


# Solve: 2x + y = 5, x + 3y = 7

A = np.array([[2, 1], [1, 3]])
b = np.array([5, 7])

x = np.linalg.solve(A, b)    # More stable than inv(A) @ b

print("Solution:", x)        # [1.6, 1.8]

# Verify: A @ x should equal b
print("Check: A @ x =", A @ x)   # [5.0, 7.0]




A + B =
 [[3 5]
 [2 8]]
A transpose =
 [[2 0]
 [1 3]]
A @ B =
 [[ 4 13]
 [ 6 15]]
Identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A inverse:
 [[ 0.6 -0.2]
 [-0.2  0.4]]
A @ A_inv =
 [[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]
Solution: [1.6 1.8]
Check: A @ x = [5. 7.]


**Exercise**

1. Create a *3×3 system of equations* from a real scenario (e.g., pricing 3 products given 3 customer orders).
2. Solve using np.linalg.solve().
3. Verify your answer.

In [16]:
import numpy as np
#orders
A = np.array([[2, 1, 3],
              [1, 2, 1],
              [3, 1, 2]])

b = np.array([19, 13, 20]) # costs
prices = np.linalg.solve(A, b)
print(prices)

[3.75 3.25 2.75]


**Identity and Inverse in NumPy**

In [20]:
#Identity and Inverse in NumPy
import numpy as np
I = np.eye(3)
print(I)
A = np.array([[2,1],[1,4]])
A_inv = np.linalg.inv(A)
print(A_inv)
print(A @ A_inv)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[ 0.57142857 -0.14285714]
 [-0.14285714  0.28571429]]
[[1. 0.]
 [0. 1.]]
